---

runtimes:
  collection: 3
  decision: 1

files:
  number: 100
  size: 100

mountpoint: 'mountpoint'

runs:
  - "zipfian"
  - "sequential"
  - "sequential"
  - "sequential"
  - "sequential"
  - "sequential"
  - "sequential"
  - "sequential"
  - "sequential"
  - "sequential"
  - "random"
  - "random"
  - "random"
  - "random"
  - "random"
  - "random"
  - "random"
  - "random"
  - "random"
  - "random"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"
  - "zipfian"